//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PqnLesson12ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PqnSACH
    {
        public string pqnqMaSach { get; set; }
        public string pqnTenSach { get; set; }
        public string pqnSoTrang { get; set; }
        public string pqnNamXB { get; set; }
        public string pqnMaTG { get; set; }
        public Nullable<bool> pqnTrangThai { get; set; }
    
        public virtual PqnTACGIA PqnTACGIA { get; set; }
    }
}
